### PR TITLE
🐛 event end

### PR DESCRIPTION
**Pull request by flying-solo**
# Description

event ended update is fixed

## screenshots
image

### CODE REVIEW

**Comment by shawshankkumar** [comment]
Hey @flying-solo please attach the mobile view too.

**Comment by flying-solo** [comment]
## mobile view 

image
image

**Review by shawshankkumar — APPROVED** [review]
LGTM. @agarwalviraj What do you think?

**Comment by flying-solo** [comment]
yup sure

**Comment by flying-solo** [comment]
image

@agarwalviraj what about this ?

**Comment by shawshankkumar** [comment]
Looks fine to me @flying-solo . @agarwalviraj what do you think?

**Comment by agarwalviraj** [comment]
Looks good 👍🏻

**Pull request merged**
